export const homeObjOne = {
    id: '1',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Get To Know Us',
    headline: 'Who We Are ?',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit debitis earum quam est ratione eos quas maiores, nesciunt quibusdam nostrum repellendus obcaecati. Eaque, quasi distinctio. Rerum alias iure quod quisquam!',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Know Us',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjTwo = {
    id: '2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'How It All Started',
    headline: 'Our Story',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit debitis earum quam est ratione eos quas maiores, nesciunt quibusdam nostrum repellendus obcaecati. Eaque, quasi distinctio. Rerum alias iure quod quisquam!',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'PiggyBank',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: '3',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Here We Are',
    headline: 'Our Process',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit debitis earum quam est ratione eos quas maiores, nesciunt quibusdam nostrum repellendus obcaecati. Eaque, quasi distinctio. Rerum alias iure quod quisquam!',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'Papers',
    dark: false,
    primary: false,
    darkText: true,
};